### ISSUE TITLE
Homebrew installation now fails..

### ISSUE THREAD

**Issue by marcb** [yokattana/json-yaml#2]
It seems your `homebrew-tap` repo has disappeared… ??? Makes installing json-yaml slightly problematic.

```
$ brew tap yokatana/tap
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Tapping yokatana/tap
Cloning into '/usr/local/Homebrew/Library/Taps/yokatana/homebrew-tap'...
Password for 'https://marcb@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/yokatana/homebrew-tap/' not found
Error: Failure while executing: git clone https://github.com/yokatana/homebrew-tap /usr/local/Homebrew/Library/Taps/yokatana/homebrew-tap --depth=1
```

**Comment by sjmulder** [comment]
Sorry for that! I found out I had misspelt my account name, so I changed it. Didn't foresee this. I'll investigate.

**Comment by yokattana** [comment]
Sorry for that! I found out I had misspelt my account name, so I changed it. Didn't foresee this. I'll investigate.

**Comment by yokattana** [comment]
I did indeed remove the tap too. I've restored it now. I didn't have the opportunity to test on Mac, so please let me know if it works.

**Comment by marcb** [comment]
✓ Works now!

Thanks

**Comment by yokattana** [comment]
Good to hear! Sorry for the inconvenience.
